import { pgTable, serial, text, integer, timestamp, jsonb } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// users table
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  uid: text("uid").notNull().unique(), // Firebase Auth UID
  email: text("email").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// quizzes table
export const quizzes = pgTable("quizzes", {
  id: text("id").primaryKey(), // uuid from frontend or server
  userId: integer("user_id")
    .references(() => users.id, { onDelete: "cascade" }), // Can be null if generated by guest before login
  title: text("title").notNull(),
  contentSource: text("content_source"),
  questions: jsonb("questions").notNull(), // JSON list of QuizQuestions
  createdAt: timestamp("created_at").defaultNow(),
});

// quiz_history table
export const quizHistory = pgTable("quiz_history", {
  id: text("id").primaryKey(),
  userId: integer("user_id")
    .references(() => users.id, { onDelete: "cascade" }), // Can be null for legacy/anonymous runs
  quizId: text("quiz_id").notNull(),
  quizTitle: text("quiz_title").notNull(),
  score: integer("score").notNull(),
  totalQuestions: integer("total_questions").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// Define relations
export const usersRelations = relations(users, ({ many }) => ({
  quizzes: many(quizzes),
  quizHistory: many(quizHistory),
}));

export const quizzesRelations = relations(quizzes, ({ one }) => ({
  user: one(users, {
    fields: [quizzes.userId],
    references: [users.id],
  }),
}));

export const quizHistoryRelations = relations(quizHistory, ({ one }) => ({
  user: one(users, {
    fields: [quizHistory.userId],
    references: [users.id],
  }),
}));
